# Generated by Django 5.1.3 on 2025-01-31 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=56)),
                ('last_name', models.CharField(max_length=40)),
                ('date_rented', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=40)),
                ('car_type', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('colour', models.CharField(max_length=30)),
                ('rented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_app', to='cars_app.person')),
            ],
        ),
    ]
