# Generated by Django 5.1.3 on 2025-01-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_rented',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='due_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
