# Generated by Django 5.1.3 on 2025-01-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0002_alter_person_date_rented_alter_person_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, upload_to='cars_image'),
        ),
        migrations.AlterField(
            model_name='person',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
